### ISSUE TITLE
Registrar todas las provincias del pais

### ISSUE THREAD

**Issue by IsaacGutierrez** [IsaacGutierrez/SearchMyHome#7]
@Lunoyo 
man, necesito de tu ayuda aquí,
por favor necesito que me registres todas las provincias de la república dominicana  en la tabla de la base de datos 
con su geolattitud y geolongitud.

debes enviarme el script que inserta los datos en SQL SERVER.
nota:
*El script de la base de datos esta en github.
*Cuando termines, cierra este issue. 
gracias.

**Comment by Lunoyo** [comment]
Ya lo vi, me pondre a eso ahora.

**Comment by Lunoyo** [comment]
@IsaacGutierrez  Me surgió una pregunta, tambien tenemos la tabla de municipios y localidad que requieren de geolocalizacion , como se llenarán estos??, ya que  una provincia tiene al menos 6 municipios y un municipio tiene aprox. 15 localidades??

**Comment by Lunoyo** [comment]
@IsaacGutierrez  Ya el nuevo script con la informacion de las provincias esta subido.

**Comment by IsaacGutierrez** [comment]
Si man hay que cargar los principales pero eso voy a tratar de hacerlo con google place API porque son demaciados. @Lunoyo

**Comment by Lunoyo** [comment]
Ha bueno perfecto, seguiré viendo los tutoriales de mvc para ayudar lo mas pronto posible.
