### ISSUE TITLE
Crear Repository Pattern para administrar multimedia 

### ISSUE THREAD

**Issue by IsaacGutierrez** [IsaacGutierrez/SearchMyHome#9]
Se debe crear un Repository pattern para administrar la multimedia, donde se deben crear dos funcionalidades concretas:

1. AzureBlobRepository
2. ServerOnPremiseRepository

**Comment by IsaacGutierrez** [comment]
Solucionado!!!

**Comment by JortegaR** [comment]
Bien ahi
